In [1]:
# Importing necessary libraries
import pandas as pd
import sqlite3
from datetime import datetime

# Configurations
DB_FILE = "retail_dw.db"
EXCEL_FILE = "Online Retail.xlsx"  # defining the Excel file name
CURRENT_DATE = pd.Timestamp("2025-08-12")  # Fixed current date for exam requirement

In [4]:
def extract_data(file_path):
    """
    Reads the Online Retail Excel into a DataFrame.
    Handles missing values and ensures correct data types.
    """
    print("Extracting data...")
    
    # Reading the Excel
    df = pd.read_excel(file_path)
    print(f"Initial rows extracted: {len(df)}")
    
    # Dropping rows with missing CustomerID
    df = df.dropna(subset=["CustomerID"])
    
    # Converting InvoiceDate to datetime
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")
    
    return df

# Running extraction
df_raw = extract_data(EXCEL_FILE)
df_raw.head()

Extracting data...
Initial rows extracted: 541909

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom